[phases.setup]
nixPkgs = ['python312']

[phases.install]
cmds = ['cd backend && pip install -r requirements.txt']

[phases.build]
cmds = ['echo "Build phase complete"']

[start]
cmd = 'cd backend && gunicorn --bind 0.0.0.0:$PORT app:app'