[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && python app.py"
healthcheckPath = "/"
healthcheckTimeout = 100

[env]
FLASK_HOST = "0.0.0.0"
FLASK_PORT = "8000"
FLASK_DEBUG = "False"